"""Investigation timeline.

Deliberately minimal (spec section 15 asks for chronological events with
source references, not a full event-correlation engine yet — that's
phase 9/10 of the roadmap, not this pass). Every event is generated by
real application actions (evidence registered, tool run, finding
created) — nothing here is simulated or backfilled.
"""
from __future__ import annotations

import itertools
import json
import time
from dataclasses import dataclass
from pathlib import Path


@dataclass
class TimelineEvent:
    event_id: str
    timestamp: float
    description: str
    source_ref: str | None = None  # EVID-XXXX, RESULT id, or F-XXXX

    def to_dict(self) -> dict:
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp,
            "description": self.description,
            "source_ref": self.source_ref,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "TimelineEvent":
        return cls(**d)


class Timeline:
    def __init__(self, case_workspace: Path) -> None:
        self.case_workspace = Path(case_workspace)
        self.timeline_dir = self.case_workspace / "timeline"
        self.timeline_dir.mkdir(parents=True, exist_ok=True)
        self._events: list[TimelineEvent] = []
        self._counter = itertools.count(1)
        self._load()

    def record(self, description: str, source_ref: str | None = None) -> TimelineEvent:
        event = TimelineEvent(
            event_id=f"T-{next(self._counter):04d}",
            timestamp=time.time(),
            description=description,
            source_ref=source_ref,
        )
        self._events.append(event)
        self._save()
        return event

    def all(self) -> list[TimelineEvent]:
        return sorted(self._events, key=lambda e: e.timestamp)

    def _save(self) -> None:
        path = self.timeline_dir / "events.json"
        path.write_text(json.dumps([e.to_dict() for e in self._events], indent=2))

    def _load(self) -> None:
        path = self.timeline_dir / "events.json"
        if not path.exists():
            return
        self._events = [TimelineEvent.from_dict(d) for d in json.loads(path.read_text())]
        self._counter = itertools.count(len(self._events) + 1)
